config/routes.rb
Mzankiety::Application.routes.draw do

  resources :surveys do
    resources :polls
    get 'votes', on: :member  
    get 'stats', on: :member  
  end

  resources :polls do
    resources :answers
    get 'vote', on: :member
    patch 'vote', on: :member
  end

  resources :polls, :surveys do
    get 'detail', on: :member
    get 'result', on: :member
    get 'setshared', on: :member
    get 'setvotable', on: :member
    patch 'setpassword', on: :member
    patch 'enddate', on: :member
  end

  resources :answers do
    get 'wipe'
    resources :votes
  end

  resources :votes

  post "/polls/:poll_id/vote", to: "votes#create"
  post "/votes", to: "votes#create"
  get "/polls/:poll_id/result", to: "polls#result"
  get 'answers', to: "answers#index"
  get 'votes', to: "votes#index"

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/views/pages/home.html.erb
<% title("Strona główna") %>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <h3><i class="fa fa-home"></i> Strona główna </h3>
    <div class="well">
      <p><b>Najnowsza ankieta:</b></p>
      <% if @survey -%>
        <p><%= link_to "#{@survey.name.slice(0,40)}...", @survey %><br>
        <%= dateformat(@survey.created_at) %></p>
      <% else %>
        <p>Brak publicznych ankiet.</p>
      <% end %>
      <%= link_to 'Nowa ankieta', new_survey_path, :class => 'btn btn-success' %>
      <%= link_to 'Pokaż wszystkie', surveys_path, :class => 'btn btn-primary' %>
      <hr>
      <p><b>Najnowsza sonda:</b></p>
      <% if @poll %>
        <p><%= link_to "#{@poll.name.slice(0,40)}...", @poll %><br>
        <%= dateformat(@poll.created_at) %></p>
      <% else %>
        <p>Brak publicznych sond.</p>
      <% end %>
      <%= link_to 'Nowa sonda', new_poll_path, :class => 'btn btn-success' %>
      <%= link_to 'Pokaż wszystkie', polls_path, :class => 'btn btn-primary' %>
    </div>  
  </div>

  <div class="col-md-4">
    <% if !user_signed_in? %>
    <h3><i class="fa fa-user"></i> Logowanie</h3>
    <div class="well">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name),
        role: "form") do |f| %>
      <div class="form-group">
        <%= f.label :username, "Użytkownik" %>
        <%= f.text_field :username, :autofocus => true, class: "form-control" %>  
      </div>
      <div class="form-group">
        <%= f.label :password, "Hasło" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <% if devise_mapping.rememberable? -%>
      <div class="form-group">
      <%= f.check_box :remember_me %> <%= f.label :remember_me, "Zapamiętaj mnie" %>
      </div>
      <% end -%>
      <%= f.submit "Zaloguj", class: "btn btn-success" %> <%= link_to "Zarejestruj", new_registration_path(resource_name) %>
      <% end %>
    </div>
    <% else %>
      <h3><i class="fa fa-user"></i> <%= current_user.username %></h3>
      <div class="well">
        <p><%= link_to '<i class="fa fa-edit fa-lg"></i> Edytuj konto'.html_safe, edit_user_registration_path %></p>
        <p><%= link_to '<i class="fa fa-close fa-lg"></i> Wyloguj'.html_safe, destroy_user_session_path, data:{method: :delete} %></p>
      </div>
    <% end %>
    Konto testowe: user1 - 1234<br>
    Do poprawnego wyświetlania wykresów zalecana aktualna przeglądarka. <br>
    Kod źródłowy <%= link_to 'tutaj.', "https://github.com/zmateusz/mzankiety" %>
  </div>

</div>

app/views/pages/inside.html.erb
<div class="row">

  <div class="col-md-10 col-md-offset-1">
    <h2>Panel użytkownika
    <small><u><%= link_to 'Nowa ankieta', new_survey_path, class:"text-success" %></u> |
    <u><%= link_to 'Nowa sonda', new_poll_path, class:"text-success" %></u></small></h2>

    <div class="well">
      <strong>Ankiety (<%= @surveys.count %>)</strong>

<% if @surveys.empty? %>
  <br>Brak utworzonych ankiet.
<% else %>
<table class="table">
  <thead>
    <tr>
      <th class="col-md-3">Nazwa</th>
      <th class="col-md-1">Data</th>
      <th class="col-md-1">Wypełnienia</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.name, detail_survey_path(survey) %></td>
        <td><%= dateformat(survey.created_at) %></td>
        <td><%= survey.votes.pluck(:voter).uniq.count %></td>
        <td><%= link_to 'Usuń', survey, method: :delete, data: { confirm: 'Na pewno?' }, class:"btn btn-danger" %></td>
        <td><%= link_to 'Pokaż', survey, method: 'get', class:"btn btn-info" %></td>
        <td><%= link_to 'Wyniki', result_survey_path(survey), method: 'get', class:"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>      

    </div>
    <div class="well">
      <strong>Sondy (<%= @polls.count %>)</strong>

<% if @polls.empty? %>
  <br>Brak utworzonych sond.
<% else %>      
<table class="table">
  <thead>
    <tr>
      <th class="col-md-3">Nazwa</th>
      <th class="col-md-1">Data</th>
      <th class="col-md-1">Głosy</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.name, detail_poll_path(poll) %></td>
        <td><%= dateformat(poll.created_at) %></td>
        <td><%= Vote.where(poll_id: poll.id).count %></td>
        <td><%= link_to 'Usuń', poll, method: :delete, data: { confirm: 'Na pewno?' }, class:"btn btn-danger" %></td>
        <td><%= button_to 'Pokaż', poll, method: 'get', class:"btn btn-info" %></td>
        <td><%= button_to 'Wyniki', result_poll_path(poll), method: 'get', class:"btn btn-success"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

    </div>
  </div>

</div>