config/routes.rb
Mzankiety::Application.routes.draw do

  resources :surveys do
    resources :polls
    get 'votes', on: :member  
    get 'stats', on: :member  
  end

  resources :polls do
    resources :answers
    get 'vote', on: :member
    patch 'vote', on: :member
  end

  resources :polls, :surveys do
    get 'detail', on: :member
    get 'result', on: :member
    get 'setshared', on: :member
    get 'setvotable', on: :member
    patch 'setpassword', on: :member
    patch 'enddate', on: :member
  end

  resources :answers do
    get 'wipe'
    resources :votes
  end

  resources :votes

  post "/polls/:poll_id/vote", to: "votes#create"
  post "/votes", to: "votes#create"
  get "/polls/:poll_id/result", to: "polls#result"
  get 'answers', to: "answers#index"
  get 'votes', to: "votes#index"

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy
  has_many :votes, through: :answers

  validates :name, :typ, presence: true
  validates :descr, length: { maximum: 500 }  
  validates :name, 
            uniqueness: true,
            length: { maximum: 70 }
end

app/controllers/polls_controller.rb
#encoding: utf-8
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy, :vote, :result]
  before_action :authenticate_user!, only: [:new]
  before_action :check_cookies, only: [:vote]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.where(survey_id: nil, shared: true).order(created_at: :desc)
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    if @poll.ends_at
      if @poll.ends_at < Time.now
        @poll.votable = false
        @poll.save
      end
    end
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    respond_to do |format|
      format.html
      format.js { render json: {success: true, response: Faker::Company.catch_phrase} }
    end
  end

  # GET /polls/1/edit
  def edit
  end

  def vote
    # render plain: params.inspect
    # redirect_to @poll, notice: 'closed' and return unless @poll.votable
    # redirect_to @poll, notice: 'closed' and return unless @poll.password == session[:pass]

    if @poll.password != "" && @poll.private
      redirect_to poll_path(@poll), notice: 'Podaj poprawne hasło aby głosować.' and return if params[:poll].nil?
      if params[:poll][:pass] != @poll.password
        redirect_to poll_path(@poll), notice: 'Podaj poprawne hasło aby głosować.' and return
      else
        session[:pass] = params[:pass]
      end
    end
    if @poll.survey != nil && session["first"] == @poll.id
      if @poll.survey.private && params[:poll][:pass] != @poll.survey.password
        redirect_to survey_path(@poll.survey_id), notice: 'Podaj poprawne hasło aby głosować.' and return
      end
    end

    # @polls = Poll.order(:id).page params[:page]

    if @poll.typ == "Radio"
      @answers = @poll.answers.order(created_at: :asc)
    elsif @poll.typ == "Checkbox"
      @answers = [] 
      @poll.answers.order(created_at: :asc).each do |answer| 
        @answers.push(answer.option)
      end
    end
        
    if @poll.survey_id != nil
      session[:prog] = 1 if session[:prog] == nil
      n = Survey.find(@poll.survey_id).polls.count
      @progress = "#{session[:prog]}/#{n}"
      @pro = (session[:prog].to_f/n*100).round(1)
      session[:prog] += 1
    end
    render layout: 'voting' 
  end

  def result
    @answers = @poll.answers
    @votes = @poll.votes.order(created_at: :desc)
    @count = @votes.count
    #@percent = Hash.new
    #@answers.each {|ans| @percent[ans.id] = (ans.counter.to_f/@count*100).round(1)}
    if @poll.typ == "Checkbox"
      @counter = @answers.sum(:counter)
      @votes_hash = Hash.new(0)
      @votes.each {|v| @votes_hash[v.custom] += 1}
    end
  end

  # POST /polls
  # POST /polls.json
  def create
    #render plain: params.inspect
    @poll = Poll.new(poll_params)
    @poll.survey_id = params[:survey_id] if params[:survey_id] != nil

    current_user == nil ? @poll.author = "anonim" : @poll.author = current_user.username

    respond_to do |format|
      if @poll.save
        format.html { 
          @poll.answers.create(option: 'custom') if @poll.typ == "Text"
          if params[:survey_id] != nil
            if @poll.typ == "Radio" || @poll.typ == "Checkbox"
              redirect_to detail_poll_path(@poll), notice: 'Pytanie zostało utworzone. Dodaj teraz odpowiedzi.'
            elsif @poll.typ == "Text" || @poll.typ == "Info"
              redirect_to detail_survey_path(params[:survey_id]), notice: 'Pytanie zostało utworzone.'
            end
          else
            redirect_to detail_poll_path(@poll), notice: 'Sonda została utworzona.' 
          end
        }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { 
          if params[:survey_id] != nil
            redirect_to detail_survey_path(params[:survey_id]), notice: 'Nie udalo sie zapisac pytania.'
          else
            render :new
          end
        }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html {
          if @poll.survey_id == nil
            redirect_to detail_poll_path(@poll), notice: 'Sonda została zaktualizowana.'
          else
            redirect_to detail_survey_path(@poll.survey_id), notice: 'Pytanie zostało zaktualizowane.'
          end 
        }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    votes = Vote.where(:poll_id => @poll.id)
    votes.each {|v| v.destroy}
    @poll.destroy
    respond_to do |format|
      format.html { 
        if @poll.survey_id == nil
          redirect_to :back, notice: 'Sonda została usunięta.'
        else
          redirect_to :back, notice: 'Pytanie zostało usunięte.'
        end
      }
      format.json { head :no_content }
    end
  end

  def setshared
    @poll = Poll.find(params[:id])
    if @poll.shared == true 
      @poll.shared = false
      @poll.save
    else
      @poll.shared = true
      @poll.save
    end
    redirect_to :back
  end

  def detail
    @poll = Poll.find(params[:id])
    @link = request.protocol + request.host_with_port + poll_path(@poll)
    @link += "?pass=#{@poll.password}" if @poll.private 
  end

  def enddate
    @poll = Poll.find(params[:id])
    end_date = params[:poll]
    if @poll.ends_at.nil?
      new_date = DateTime.new(end_date["created_at(1i)"].to_i,
                          end_date["created_at(2i)"].to_i,
                          end_date["created_at(3i)"].to_i,
                          end_date["created_at(4i)"].to_i-1, #poprawka do strefy czasowej, inny sposob?
                          end_date["created_at(5i)"].to_i)
    else
      new_date = DateTime.new(end_date["ends_at(1i)"].to_i,
                          end_date["ends_at(2i)"].to_i,
                          end_date["ends_at(3i)"].to_i,
                          end_date["ends_at(4i)"].to_i-1,
                          end_date["ends_at(5i)"].to_i)
    end
    @poll.update_attribute(:votable, false) if new_date < Time.now
    @poll.update_attribute(:ends_at, new_date)
    redirect_to :back
  end

  def setvotable
    @poll = Poll.find(params[:id])
    if @poll.votable == true 
      @poll.votable = false
      @poll.save
    else
      @poll.votable = true
      @poll.save
    end
    redirect_to :back
  end

  def setpassword
    @poll = Poll.find(params[:id])
    @poll.password = params[:poll][:password]
    if params[:poll][:password].empty?
      @poll.private = false
    else 
      @poll.private = true
    end
    @poll.save
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :typ, :descr, :survey_id)
    end
end

app/helpers/polls_helper.rb
#encoding: utf-8
module PollsHelper

  def shared_poll(poll)
    if poll.shared == true
      "Udostępniona - #{link_to 'Ukryj', setshared_poll_path(@poll), method: 'get'}" 
    else
      "Ukryta - #{link_to 'Udostępnij', setshared_poll_path(@poll), method: 'get'}"
    end
  end

  def votable_poll(poll)
    if poll.votable == true
      "Otwarta - #{link_to 'Zamknij', setvotable_poll_path(@poll), method: 'get'}" 
    else
      "Zamknięta - #{link_to 'Otwórz', setvotable_poll_path(@poll), method: 'get'}"
    end
  end

  def typeinfo(typ)
    if typ == "Radio"
      "Wybór jednokrotny"
    elsif typ == "Checkbox"
      "Wybór wielokrotny"
    elsif typ == "Text"
      "Dowolny tekst"
    elsif typ == "Info"
      "Puste pytanie"
    end
  end

end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <a class="btn btn-primary" id="aaa" onclick="getRandom();">Random name</a> -->
  
  <div class="form-group"> 
  <div class="field" style="width:100%">
    <%= f.label :name, "Nazwa/Pytanie" %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="field" style="width:100%">
    <%= f.label :descr, "Opis" %><br>
    <%= f.text_area :descr , class: "form-control"%>
  </div>
  <div class="field" style="width:40%">
    <%= f.label 'Typ' %><br>
    <select size="4" class="form-control" name="poll[typ]" id="poll_typ">
    <option value="Radio" selected="selected">Wybór jednokrotny</option>
    <option value="Checkbox">Wybór wielokrotny</option>
    <option value="Text">Dowolny tekst</option>
    <% unless @poll.survey_id.nil? %><option value="Info">Puste pytanie</option><% end %>
    </select>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz", class: "btn btn-success"%>
  </div>
<% end %>

<script>
  function getRandom(){
    $.ajax({
      url: '/polls/new',
      dataType: 'json',
      type: 'GET',
      success: function(data){
        document.getElementById('poll_name').value = data['response'];
      }
    });

  };
</script>

app/views/polls/detail.html.erb
<div class="row">
<div class="col-md-1"></div>

<div class="col-md-7">
<p id="notice"></p>
<p>
  <h3><%= if @poll.survey then "Pytanie:" else "Sonda:" end %> <%= @poll.name %></h3>
  <strong>Data utworzenia:</strong> <%= dateformat(@poll.created_at) %> |
  <%= link_to 'Edytuj', edit_poll_path(@poll) %> |
  <%= link_to 'Powrót do ankiety', detail_survey_path(@poll.survey) if @poll.survey %>
  <%= link_to 'Powrót', inside_path unless @poll.survey %>
</p>
<% unless @poll.survey %><input type="text" value="<%= @link %>" style="width:60%"></input>
<% end %>
<p>
  <strong>Opis:</strong> <%= raw @poll.descr %>
</p>
  <strong>Typ:</strong>
  <%= typeinfo(@poll.typ) %>
<hr>
<% if (@poll.typ != "Text") && (@poll.typ != "Info") -%>
<h4>Odpowiedzi</h4>
<% if @poll.answers.empty? -%>
  <p class="text-danger"><b>Brak odpowiedzi. Dodaj jedną poniżej:</b></p>
<% else %>
<ul>
<% @poll.answers.order(created_at: :asc).each do |answer| %>
  <li>
    <%= answer.option %> |
    <%= link_to 'Usuń', answer_path(:id => answer.id, :poll => @poll.id), method: :delete, data: { confirm: 'Na pewno?' }  %>
  </li>
<% end %>
</ul>
<% end %>


<h4>Nowa odpowiedź:</h4>
<%= form_for([@poll, @poll.answers.build]) do |f| %>
  <p>
    <%# f.label :opcja %>
    <%# :value => Faker::Name.first_name %>
    <%= f.text_field :option, class: "form-control", style: "width:80%"%>
  </p>
  <p>
    <%= f.submit "Dodaj odpowiedź", class: "btn btn-success" %>
  </p>
<% end %>
<% end %>
</div>

<div class="col-md-4">
<% unless @poll.survey_id.present? %>
  <h3>Ustawienia</h3>

  <b>Data zakończenia:</b><br>
  <% if @poll.ends_at.nil? %>
    nie ustawiono
    <%= form_for @poll, url: {action: "enddate"} do |f| %>
    <%= f.date_select :created_at, :start_year => @poll.created_at.year %><br> 
    <%= f.time_select :created_at, :ignore_date => true %>
    <%= f.submit "Ustaw datę" %>
    <% end %>
  <% else %>
    <%= dateformat(@poll.ends_at) %>
    (<%= distance_of_time_in_words(@poll.ends_at, Time.now) %>)
    <%= form_for @poll, url: {action: "enddate"} do |f| %>
    <%= f.date_select :ends_at, :start_year => @poll.created_at.year%><br> 
    <%= f.time_select :ends_at, :ignore_date => true %>
    <%= f.submit "Ustaw datę" %>
    <% end %>
  <% end %>
<br>
<p><b>Widoczność:</b> <%= raw shared_poll(@poll) %></p>
<p><b>Status:</b> <%= raw votable_poll(@poll) %></p>
<p><b>Hasło dostępu:</b>
  <%= form_for @poll, url: {action: "setpassword"} do |f| %>
    <%= f.text_field :password %><br>
    <%= f.submit "Ustaw hasło" %>
  <% end %>
</p>
<% end %>
</div>
</div>

app/views/polls/edit.html.erb
<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8"><br>
<div class="well">
<h3><%= @poll.survey_id.nil? ? "Edycja sondy" : "Edycja pytania" %></h3>

<%= render 'form' %>

<br>
<%= link_to 'Pokaż', @poll %> |
<%= link_to 'Powrót', detail_poll_path(@poll) %>
</div>
</div>

<div class="col-md-2"></div>
</div>

app/views/polls/index.html.erb
<% title("Sondy") %>

<div class="row">
<div class="col-md-2"><%= cookies["dfdf"] %></div>

<div class="col-md-8">
<h2>Sondy <small><u><%= link_to 'Nowa sonda', new_poll_path, class:"text-success" %></u></small></h2>

<% if @polls.empty? %>
  <p>Brak sond.</p>
<% else %>
<table class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-4">Nazwa</th>
      <th class="col-md-2">Data utworzenia</th>
      <th class="col-md-1">Typ</th>
      <th class="col-md-1">Autor</th>
    </tr>
  </thead>
  
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.name, poll %></td>
        <td><%= dateformat(poll.created_at) %></td>
        <td><%= typeinfo(poll.typ) %></td>
        <td><%= poll.author %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%# paginate @polls %>
</div>
</div>

app/views/polls/new.html.erb
<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8"><br>
<div class="well">
  <h2>Nowa sonda</h2>

  <%= render 'form' %>

  <%= link_to 'Powrót', polls_path %>
</div>
</div>

<div class="col-md-2"></div>
</div>

app/views/polls/result.html.erb
<%= javascript_include_tag "http://www.google.com/jsapi" %>
<%= javascript_include_tag "application", "chartkick" %>
<div class="row">

  <div class="col-md-8 col-md-offset-2">
    <h4><%=raw @poll.survey.nil? ? "Wyniki dla sondy" : "Wyniki dla pytania 
    | <u>#{link_to 'Powrót do wyników ankiety', result_survey_path(@poll.survey), class:"text-success"}</u>" %></h4>
    <h4><%= @poll.name %></h4>
    <%= render "layouts/#{@poll.typ.downcase}" %>
  </div>

</div>

app/views/polls/show.html.erb
<%= javascript_include_tag "http://www.google.com/jsapi" %>
<%= javascript_include_tag "application", "chartkick" %>
<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8">
<p id="notice"></p>

<div class="well">
<h3>Sonda: <%= @poll.name %></h3>
<hr>
<p>
  <strong>Opis:</strong> <%=raw @poll.descr %>
</p>
<dl class="dl-horizontal">
  <dt>Autor:</dt>
  <dd><%= @poll.author %></dd>
  <dt>Typ:</dt>
  <dd><%= typeinfo(@poll.typ) %></dd>
  <dt>Data utworzenia:</dt>
  <dd><%= dateformat(@poll.created_at) %></dd>
  <dt>Data zakończenia:</dt>
  <dd><%= @poll.ends_at.nil? ? "brak" : dateformat(@poll.ends_at) %></dd>
</dl>

<% if @poll.votable %>
<% if @poll.private %>
<%= form_for @poll, url: {action: "vote"} do |f|%>
  <p class="text-center">
    <%= f.text_field :pass, :value => params[:pass] %> 
    <%= f.submit "Wypełnij", class:"btn btn-success "%>
  </p>
<% end %>
<% else %>
<p class="text-center">
<%= link_to 'Wypełnij', vote_poll_path(@poll), method: 'get', class:"btn btn-success"%>
</p>
<% end %>
<% end %>
<%# pie_chart @ans.group(:option).sum(:counter) if @poll.typ == "Radio" %>
<hr>
<p class="text-center"><%= link_to "Pokaż szczegóły", detail_poll_path(@poll) if current_user && current_user.username == @poll.author%></p>

</div>
</div>

<div class="col-md-2"></div>
</div>

app/views/polls/vote.html.erb
<div class="row">
  <div class="col-md-3">
    <!-- <br><img src="http://placekitten.com/g/251/400"> -->
  </div>
  <div class="col-md-6">
<br><br>
<div class="well">
<h3><%= @poll.name %></h3>
  <%= raw @poll.descr %>
  <% case @poll.typ %>
  <% when "Radio"%>
  <div class="col-md-offset-2"><br>
  <%= form_for :vote do |f| %><h4>
    <% @answers.each do |answer| %>
      <%= radio_button_tag(:vote, answer.id) %>
      <%= label_tag("vote_#{answer.id}", answer.option) %><br>
      <% end %><br>
    <%= f.submit "Dalej", class: 'btn btn-primary'%></h4>
    <% end %>
  <% when "Checkbox"%>
  <div class="col-md-offset-2"><br>
    <%= simple_form_for :vote do |f| %>
    <%= f.input :choices, as: :check_boxes, collection: @answers, label: false%><br>
    <%= f.button :submit, "Dalej", class: 'btn btn-primary'%>
    <% end %>
  <% when "Text"%>
  <div class="col-md-offset-1"><br>
    <%= form_for :vote do |f| %>  
    <p><%= f.text_area :vote , class: "form-control", style: "width:90%" %></p>
    <%= f.submit "Dalej", class: 'btn btn-primary'%>
    <% end %>
  <% when "Info"%>
  <div class="col-md-offset-2"><br>
    <%= form_for :vote do |f| %> 
    <%= f.submit "Dalej", class: 'btn btn-primary'%>
    <% end %>
  <% end %>

  <%= @progress %>
  <div class="progress" style="width:25%;">
    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @pro %>%;">
    <span class="sr-only">60% Complete</span>
    </div>
  </div>

  </div>
  </div>

  </div>
  <div class="col-md-3"></div>
</div>
