config/routes.rb
Mzankiety::Application.routes.draw do

  resources :surveys do
    resources :polls
    get 'votes', on: :member  
    get 'stats', on: :member  
  end

  resources :polls do
    resources :answers
    get 'vote', on: :member
    patch 'vote', on: :member
  end

  resources :polls, :surveys do
    get 'detail', on: :member
    get 'result', on: :member
    get 'setshared', on: :member
    get 'setvotable', on: :member
    patch 'setpassword', on: :member
    patch 'enddate', on: :member
  end

  resources :answers do
    get 'wipe'
    resources :votes
  end

  resources :votes

  post "/polls/:poll_id/vote", to: "votes#create"
  post "/votes", to: "votes#create"
  get "/polls/:poll_id/result", to: "polls#result"
  get 'answers', to: "answers#index"
  get 'votes', to: "votes#index"

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :polls, dependent: :destroy
  has_many :votes, through: :polls

  validates :name, 
            presence: true, 
            uniqueness: true,
            length: { maximum: 70 }
  validates :descr, length: { maximum: 500 }      
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :result, :votes, :stats]
  before_action :authenticate_user!, only: [:new]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.where(shared: true).order(created_at: :desc)
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @firstpoll = @survey.polls.first
    session["first"] = @firstpoll.id if @firstpoll
    session[:prog] = nil
    if @survey.ends_at
      if @survey.ends_at < Time.now
        @survey.votable = false
        @survey.save
      end
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    if current_user == nil
      @survey.author = "anonim"
    else
      @survey.author = current_user.username
    end
    respond_to do |format|
      if @survey.save
        format.html { redirect_to detail_survey_path(@survey), notice: 'Ankieta zostala utworzona.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to detail_survey_path(@survey), notice: 'Ankieta zostala pomyslnie zaktualizowana.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.polls.each do |poll|
      poll.destroy
    end
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to inside_url, notice: 'Ankieta zostala pomyslnie skasowana.' }
      format.json { head :no_content }
    end
  end

  def setshared
    @survey = Survey.find(params[:id])
    if @survey.shared == true 
      @survey.shared = false
      @survey.save
    else
      @survey.shared = true
      @survey.save
    end
    redirect_to detail_survey_path(@survey)
  end

  def enddate
    detail
    end_date = params[:survey]
    if @survey.ends_at.nil?
      new_date = DateTime.new(end_date["created_at(1i)"].to_i,
                          end_date["created_at(2i)"].to_i,
                          end_date["created_at(3i)"].to_i,
                          end_date["created_at(4i)"].to_i-1, #poprawka do strefy czasowej, inny sposob?
                          end_date["created_at(5i)"].to_i)
    else
      new_date = DateTime.new(end_date["ends_at(1i)"].to_i,
                          end_date["ends_at(2i)"].to_i,
                          end_date["ends_at(3i)"].to_i,
                          end_date["ends_at(4i)"].to_i-1,
                          end_date["ends_at(5i)"].to_i)
    end
    @survey.update_attribute(:votable, false) if new_date < Time.now
    @survey.update_attribute(:ends_at, new_date)
    redirect_to :back
  end

  def setvotable
    @survey = Survey.find(params[:id])
    if @survey.votable == true 
      @survey.votable = false
      @survey.save
    else
      @survey.votable = true
      @survey.save
    end
    redirect_to :back
  end

  def setpassword
    @survey = Survey.find(params[:id])
    @survey.password = params[:survey][:password]
    @survey.polls.each do |poll|
      poll.password = @survey.password
      poll.save
    end
    if params[:survey][:password].empty?
      @survey.private = false
    else 
      @survey.private = true
    end
    @survey.save
    redirect_to :back
  end

  def detail
    @survey = Survey.find(params[:id])
    @link = request.protocol + request.host_with_port + survey_path(@survey)
    @link += "?pass=#{@survey.password}" if @survey.private 
  end

  def result
    @polls = @survey.polls.order(created_at: :asc)
  end

  def votes
    @votes = @survey.votes
    @ids = @votes.pluck(:voter).uniq
    @voters = Hash.new(0)
    @ids.each {|id| @voters[id] = []}
    @voters.each do |k,v|
      temp = @votes.where(voter: k).last
      @voters[k].push(temp.author, temp.created_at)
    end
  end

  def stats
    @polls = @survey.polls.order(created_at: :asc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :descr, :author)
    end
end

app/helpers/surveys_helper.rb
#encoding: utf-8
module SurveysHelper

  def shared_survey(survey)
    if survey.shared == true
      "Udostępniona - #{link_to 'Ukryj', setshared_survey_path(@survey), method: 'get'}" 
    else
      "Ukryta - #{link_to 'Udostępnij', setshared_survey_path(@survey), method: 'get'}"
    end
  end

  def votable_survey(survey)
    if survey.votable == true
      "Otwarta - #{link_to 'Zamknij', setvotable_survey_path(@survey), method: 'get'}" 
    else
      "Zamknięta - #{link_to 'Otwórz', setvotable_survey_path(@survey), method: 'get'}"
    end
  end

end

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey) do |f| %>
  <h4><%= f.error_notification %></h4>
  <% @survey.errors.full_messages.each do |message| %>
    <span class="text-danger"><%= message %></span><br>
  <% end %><br>

  <div class="form-inputs">
    <%= f.label :name, "Nazwa" %><br>
    <%= f.text_field :name, class: "form-control", style: "width:100%"%>
    <%= f.label :descr, "Opis" %><br>
    <%= f.text_area :descr, class: "form-control", style: "width:100%" %>
  </div>

  <div class="form-actions">
    <br><%= f.button :submit, value: "Zapisz", class: "btn btn-success" %>
  </div>
<% end %>

app/views/surveys/detail.html.erb
<div class="row">
<div class="col-md-1"></div>

<div class="col-md-7">
<p id="notice"></p>
<p>
  <h3>Ankieta: <%= @survey.name %></h3>
  <strong>Data utworzenia:</strong> <%= dateformat(@survey.created_at) %> |
  <%= link_to 'Edytuj', edit_survey_path(@survey) %> |
  <%= link_to 'Powrót', inside_path %>
</p>
<input type="text" value="<%= @link %>" style="width:60%"></input>
<p>
  <strong>Opis:</strong> <%= raw @survey.descr %>
</p>
<hr>
<% if @survey.polls.empty? -%>
  <p class="text-danger"><b>Brak pytań. Dodaj jedno poniżej:</b></p>
<% else %>
  <table class="table table-hover">
    <thead>
    <tr>
      <th class="col-md-3"><h4>Pytania</h4></th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody><% i=1 %>
    <% @survey.polls.order(created_at: :asc).each do |poll| %>
      <tr>
        <td><%= "#{i}." %><% i+=1 %> <%= link_to poll.name, detail_poll_path(poll), class: "text-info"%></td>
        <td><%= typeinfo(poll.typ) %> <%# "(brak odpowiedzi!)" if poll.typ == "Radio" && poll.answers.empty? %></td>
        <td><%= link_to "Edytuj", edit_poll_path(poll), class: "text-primary" %></td>
        <td><%= link_to 'Usuń', poll, method: :delete, data: { confirm: 'Na pewno?' }, class:"text-danger" %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

<h4>Dodaj pytanie:</h4>
<%= form_for([@survey, @survey.polls.build]) do |f| %>
  <div class="form-group"> 
  <div class="field" style="width:80%">
    <%= f.label :name, "Nazwa" %><br>
    <%= f.text_field :name , class: "form-control" %>
    <!-- , :value => Faker::Company.catch_phrase -->
  </div>
  <div class="field" style="width:80%">
    <%= f.label :descr, "Opis" %><br>
    <%= f.text_area :descr , class: "form-control"%>
    <!-- , :value => Faker::Lorem.sentence -->
  </div>
  <div class="field" style="width:40%">
    <%= f.label 'Typ' %><br>
    <select size="4" class="form-control" name="poll[typ]" id="poll_typ">
    <option value="Radio" selected="selected">Wybór jednokrotny</option>
    <option value="Checkbox">Wybór wielokrotny</option>
    <option value="Text">Dowolny tekst</option>
    <option value="Info">Puste pytanie</option>
    </select>
  </div>
  <%= hidden_field_tag(:survey_id, @survey.id) %>
  </div>
  <div class="actions">
    <%= f.submit "Dodaj pytanie", class: "btn btn-success"%>
  </div>
<% end %>

</div>

<div class="col-md-4">
  <h3>Ustawienia</h3>

  <b>Data zakończenia:</b><br>
  <% if @survey.ends_at.nil? %>
    nie ustawiono
    <%= form_for @survey, url: {action: "enddate"} do |f| %>
    <%= f.date_select :created_at, :start_year => @survey.created_at.year %><br> 
    <%= f.time_select :created_at, :ignore_date => true %>
    <%= f.submit "Ustaw datę" %>
    <% end %>
  <% else %>
    <%= dateformat(@survey.ends_at) %>
    (<%= distance_of_time_in_words(@survey.ends_at, Time.now) %>)
    <%= form_for @survey, url: {action: "enddate"} do |f| %>
    <%= f.date_select :ends_at, :start_year => @survey.created_at.year%><br> 
    <%= f.time_select :ends_at, :ignore_date => true %>
    <%= f.submit "Ustaw datę" %>
    <% end %>
    <%= "zakończono" if @survey.ends_at < Time.now %>
  <% end %>
<br>
<p><b>Widoczność:</b> <%= raw shared_survey(@survey) %></p>
<p><b>Status:</b> <%= raw votable_survey(@survey) %></p>
<p><b>Hasło dostępu:</b>
  <%= form_for @survey, url: {action: "setpassword"} do |f| %>
    <%= f.text_field :password %><br>
    <%= f.submit "Ustaw hasło" %>
  <% end %>
</p>
</div>
</div>

app/views/surveys/edit.html.erb
<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8"><br>
<div class="well">
<h2>Edycja ankiety</h2>

<%= render 'form' %>

<br>
<%= link_to 'Pokaż', @survey %> |
<%= link_to 'Powrót', detail_survey_path(@survey) %>
</div>
</div>

<div class="col-md-2"></div>
</div>

app/views/surveys/index.html.erb
<% title("Ankiety") %>

<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8">

<h2>Ankiety <small><u><%= link_to 'Nowa ankieta', new_survey_path, class:"text-success" %></u></small></h2>

<% if @surveys.empty? %>
  <p>Brak ankiet.</p>
<% else %>
<table class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-7">Nazwa</th>
      <th class="col-md-3">Data utworzenia</th>
      <th class="col-md-2">Autor</th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.name, survey %></td>
        <td><%= dateformat(survey.created_at) %></td>
        <td><%= survey.author %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

</div>
</div>

app/views/surveys/new.html.erb
<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8">
<br>
<div class="well">
<h2>Nowa ankieta</h2>

<%= render 'form' %>

<%= link_to 'Powrót', surveys_path %>
</div>
</div>

<div class="col-md-2"></div>
</div>

app/views/surveys/result.html.erb
<div class="row">

  <div class="col-md-8 col-md-offset-2">
    <h4>Wyniki dla ankiety:</h4>
    <h4><%= @survey.name %></h4>

<div role="tabpanel">
  <!-- Nav tabs nav-stacked, nav-pills or nav-tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#stats" aria-controls="stats" role="tab" data-toggle="tab">Pytania</a></li>
    <li role="presentation"><%= link_to "Głosy", votes_survey_path(@survey) %></li>
    <li role="presentation"><%= link_to "Statystyki", stats_survey_path(@survey) %></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="result">
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Pytanie</th>
            <th>Typ</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @polls.each do |poll| %>
            <tr>
              <td><%= poll.name %></td>
              <td><%= typeinfo(poll.typ) %></td>
              <td><%= link_to 'Wyniki', result_poll_path(poll), class:"btn btn-success" unless poll.typ == "Info" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

  </div>
</div>

app/views/surveys/show.html.erb
<div class="row">
<div class="col-md-2"></div>

<div class="col-md-8">
<p id="notice"></p>

<div class="well">
<h3>Ankieta: <%= @survey.name %></h3>
<hr>
<p>
  <strong>Opis:</strong> <%= raw @survey.descr %>
</p>
<dl class="dl-horizontal">
  <dt>Autor:</dt>
  <dd><%= @survey.author %></dd>
  <dt>Data utworzenia:</dt>
  <dd><%= dateformat(@survey.created_at) %></dd>
  <dt>Data zakończenia:</dt>
  <dd><%= @survey.ends_at.nil? ? "brak" : dateformat(@survey.ends_at) %></dd>
</dl>

<% if @survey.votable %>
<% if @survey.private %>
<%= form_for @firstpoll, url: {controller: "polls", action: "vote", id: @firstpoll.id} do |f|%>
  <p class="text-center">
    <%= f.text_field :pass, :value => params[:pass] %> 
    <%= f.submit "Wypełnij", class:"btn btn-success "%>
  </p>
<% end %>
<% else %>
<p class="text-center">
<%= link_to 'Wypełnij', vote_poll_path(@firstpoll), method: 'get', class:"btn btn-success"%>
</p>
<% end %>
<% end %>
<hr>
<p class="text-center"><%= link_to "Pokaż szczegóły", detail_survey_path(@survey) if current_user && current_user.username == @survey.author %></p>
</div>

</div>

<div class="col-md-2"></div>
</div>

app/views/surveys/stats.html.erb
<%= javascript_include_tag "http://www.google.com/jsapi" %>
<%= javascript_include_tag "application", "chartkick" %>
<%# javascript_include_tag "highcharts.js", "chartkick" %>
<div class="row">

  <div class="col-md-8 col-md-offset-2">
    <h4>Wyniki dla ankiety:</h4>
    <h4><%= @survey.name %></h4>

<div role="tabpanel">
  <!-- Nav tabs nav-stacked, nav-pills or nav-tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><%= link_to "Pytania", result_survey_path(@survey) %></li>
    <li role="presentation"><%= link_to "Głosy", votes_survey_path(@survey) %></li>
    <li role="presentation" class="active"><a href="#stats" aria-controls="stats" role="tab" data-toggle="tab">Statystyki</a></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="result">

      <% @polls.each do |poll| %>
        <% case poll.typ %>
        <% when "Radio" %>
        <h4><%= poll.name %></h4>
        <%= bar_chart poll.answers.group(:option).sum(:counter), colors: ["##{rand(100..999)}"] %>
        <% when "Checkbox" %>
        <h4><%= poll.name %></h4>
        <% @v = Hash.new(0); poll.votes.each {|v| @v[v.custom] += 1} %>
        <%= bar_chart @v, colors: ["##{rand(100..999)}"] %>
        <% when "Text" %>
        <h4><%= poll.name %></h4>
        <%= link_to "Pokaż wszystkie", result_poll_path(poll) %>
          <% poll.votes.limit(5).each do |vote| %>
            <blockquote><%= vote.custom %>, <%= vote.author %></blockquote>
          <% end %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

  </div>
</div>

app/views/surveys/votes.html.erb
<div class="row">

  <div class="col-md-8 col-md-offset-2">
    <h4>Wyniki dla ankiety:</h4>
    <h4><%= @survey.name %></h4>

<div role="tabpanel">
  <!-- Nav tabs nav-stacked, nav-pills or nav-tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><%= link_to "Pytania", result_survey_path(@survey) %></li>
    <li role="presentation" class="active"><a href="#stats" aria-controls="stats" role="tab" data-toggle="tab">Głosy</a></li>
    <li role="presentation"><%= link_to "Statystyki", stats_survey_path(@survey) %></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="result">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Użytkownik</th>
            <th>Data</th>
            <th>Głosy</th>
          </tr>
        </thead>

        <tbody>
          <% @voters.sort_by{|k, v| k}.each do |k,v| %>
            <tr>
              <td><%= k %></td>
              <td><%= v[0] %></td>
              <td><%= dateformat(v[1]) %></td>
              <td>

              <button class="btn btn-primary" data-toggle="modal" data-target="#voter-<%= k %>">Pokaż</button>

              <div class="modal" id="voter-<%= k %>" tabindex="-1" role="dialog" aria-labelledby="voter-<%= k %>-label" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title" id="voter-<%= k %>-label"><%= "Użytkownik: #{v[0]}, data: #{dateformat(v[1])}"%></h4>
                    </div>
                    <div class="modal-body">
                      <% @votes.where(voter: k).order(created_at: :asc).each do |vote| %>
                        <p><h4><%= vote.poll.name %></h4>
                        <blockquote><p><%= vote.custom %></p></blockquote></p>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-dismiss="modal">Zamknij</button>
                    </div>
                  </div>
                </div>
              </div>


              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

  </div>
</div>