config/routes.rb
Mzankiety::Application.routes.draw do

  resources :surveys do
    resources :polls
    get 'votes', on: :member  
    get 'stats', on: :member  
  end

  resources :polls do
    resources :answers
    get 'vote', on: :member
    patch 'vote', on: :member
  end

  resources :polls, :surveys do
    get 'detail', on: :member
    get 'result', on: :member
    get 'setshared', on: :member
    get 'setvotable', on: :member
    patch 'setpassword', on: :member
    patch 'enddate', on: :member
  end

  resources :answers do
    get 'wipe'
    resources :votes
  end

  resources :votes

  post "/polls/:poll_id/vote", to: "votes#create"
  post "/votes", to: "votes#create"
  get "/polls/:poll_id/result", to: "polls#result"
  get 'answers', to: "answers#index"
  get 'votes', to: "votes#index"

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/views/layouts/_checkbox.html.erb
<div role="tabpanel">
  <!-- Nav tabs nav-stacked, nav-pills or nav-tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#stats" aria-controls="stats" role="tab" data-toggle="tab">Statystyki</a></li>
    <li role="presentation"><a href="#charts" aria-controls="charts" role="tab" data-toggle="tab">Wykresy</a></li>
    <li role="presentation"><a href="#votes" aria-controls="votes" role="tab" data-toggle="tab">Głosy</a></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="stats">
      <br><p><b>Wszystkich głosów: <%= @count %></b></p>
      <p>
        <% @votes_hash.sort_by{|k, v| v}.reverse.each do |k,v| %>
        <%= "#{k}: #{v}" %>
        <% @p = (v.to_f/@count*100).round(1) %>(<%= @p %>%)
        <div class="progress" style="width:80%">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @p %>%;">
        </div>
        </div>
        <% end %>
      </p>

      <table class="table table-hover table-bordered" style="width:80%">
        <thead>
          <tr>
            <th class="col-md-4">Odpowiedź</th>
            <th class="col-md-1">Głosy</th>
            <th class="col-md-1">Procenty</th>
          </tr>
        </thead>
        <tbody>
       <% @votes_hash.each do |k,v| %>
       <tr>
        <td><%= k %></td>
        <td><%= v %></td>
        <td><% @p = (v.to_f/@count*100).round(1) %><%= @p %>%</td>
      <tr>
       <% end %>
       </tbody>
      </table>       

      <hr><b>Statystyki odpowiedzi:</b><br><br>
      <% @answers.order(counter: :desc).each do |answer| %>
      <%= answer.option %>: <%= answer.counter %>
      <% @p = (answer.counter.to_f/@counter*100).round(1) %>(<%= @p %>%)
      <div class="progress" style="width:80%">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @p %>%;">
      </div>
      </div>
      <% end %>

      <table class="table table-hover table-bordered" style="width:60%">
        <thead>
          <tr>
            <th class="col-md-2">Odpowiedź</th>
            <th class="col-md-1">Głosy</th>
            <th class="col-md-1">Procenty</th>
          </tr>
        </thead>
        <tbody>
       <% @answers.order(created_at: :asc).each do |answer| %>
       <tr>
        <td><%= answer.option %></td>
        <td><%= answer.counter %></td>
        <td><% @p = (answer.counter.to_f/@counter*100).round(1) %><%= @p %>%</td>
      <tr>
       <% end %>
       </tbody>
      </table> 

    </div>

    <div role="tabpanel" class="tab-pane" id="charts">
      <br><b>Głosy:</b>
      <%= pie_chart @votes_hash %>
      <%= bar_chart @votes_hash %>
      <b>Pojedyncze odpowiedzi:</b>
      <%= pie_chart @answers.group(:option).sum(:counter) %>

    </div>

    <div role="tabpanel" class="tab-pane" id="votes">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Odpowiedź</th>
            <th>Użytkownik</th>
            <th>Data</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @votes.each do |vote| %>
            <tr>
              <td><%= vote.custom %></td>
              <td><%= vote.author %></td>
              <td><%= dateformat(vote.created_at) %></td>
              <td><%= link_to 'Usuń', vote, method: :delete, data: { confirm: 'Na pewno?' }%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    
    <div class="row footer-first-row">
      
      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2015 - zmateusz
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net", style: 'color:#222;' %>
        </small></p>
      </div>
      
    </div>
    
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# link_to 'Strona główna', root_path, class: 'navbar-brand' %>
      <a href="/" class="navbar-brand"><i class="fa fa-home fa-lg"></i> Strona główna</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="<%= 'active' if current_page?(surveys_path) %>"><%= link_to '<i class="fa fa-file-o fa-lg"></i> Ankiety'.html_safe, surveys_path %></li>
<li class="<%= 'active' if current_page?(polls_path) %>"><%= link_to '<i class="fa fa-question-circle fa-lg"></i> Sondy'.html_safe, polls_path %></li>
<% if !user_signed_in? %>
<li class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to '<i class="fa fa-user fa-lg"></i> Zaloguj'.html_safe, new_user_session_path %></li>
<li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to '<i class="fa fa-plus fa-lg"></i> Zarejestruj'.html_safe, new_user_registration_path %></li>
<% else %>
<li class="<%= 'active' if current_page?(inside_path) %>"><%= link_to '<i class="fa fa-laptop fa-lg"></i> Panel'.html_safe, inside_path %></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user fa-lg"></i> <%= current_user.username %> <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <% if current_user.admin? %>
      <li><%= link_to '<i class="fa fa-star-o fa-lg"></i> Admin'.html_safe, admin_root_path %></li>
      <li><%= link_to '<i class="fa fa-check-square-o fa-lg"></i> Odpowiedzi'.html_safe, answers_path %></li>
      <li><%= link_to '<i class="fa fa-comments fa-lg"></i> Głosy'.html_safe, votes_path %></li>
    <% end %>
    <li><%= link_to '<i class="fa fa-edit fa-lg"></i> Edytuj konto'.html_safe, edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><%= link_to '<i class="fa fa-close fa-lg"></i> Wyloguj'.html_safe, destroy_user_session_path, data:{method: :delete} %></li>
  </ul>
</li>
<% end %>

app/views/layouts/_radio.html.erb
<div role="tabpanel">
  <!-- Nav tabs nav-stacked, nav-pills or nav-tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#stats" aria-controls="stats" role="tab" data-toggle="tab">Statystyki</a></li>
    <li role="presentation"><a href="#charts" aria-controls="charts" role="tab" data-toggle="tab">Wykresy</a></li>
    <li role="presentation"><a href="#votes" aria-controls="votes" role="tab" data-toggle="tab">Głosy</a></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="stats">
      <br><p><b>Wszystkich głosów: <%= @count %></b></p>
      <p>
        <% @answers.order(counter: :desc).each do |answer| %>
        <%= answer.option %>: <%= answer.counter %>
        <% @p = (answer.counter.to_f/@count*100).round(1) %>(<%= @p %>%)
        <div class="progress" style="width:80%">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @p %>%;">
        </div>
        </div>
        <% end %>
      </p>

      <table class="table table-hover table-bordered" style="width:60%">
        <thead>
          <tr>
            <th class="col-md-2">Odpowiedź</th>
            <th class="col-md-1">Głosy</th>
            <th class="col-md-1">Procenty</th>
          </tr>
        </thead>
        <tbody>
       <% @answers.order(created_at: :asc).each do |answer| %>
       <tr>
        <td><%= answer.option %></td>
        <td><%= answer.counter %></td>
        <td><% @p = (answer.counter.to_f/@count*100).round(1) %><%= @p %>%</td>
      <tr>
       <% end %>
       </tbody>
      </table> 

    </div>

    <div role="tabpanel" class="tab-pane" id="charts">
      <%= pie_chart @answers.group(:option).sum(:counter) %>
      <%= column_chart @answers.group(:option).sum(:counter) %>
      <%= bar_chart @answers.group(:option).sum(:counter) %>
    </div>

    <div role="tabpanel" class="tab-pane" id="votes">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Odpowiedź</th>
            <th>Użytkownik</th>
            <th>Data</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @votes.each do |vote| %>
            <tr>
              <td><%= vote.answer.option if vote.answer%></td>
              <td><%= vote.author %></td>
              <td><%= dateformat(vote.created_at) %></td>
              <td><%= link_to 'Usuń', vote, method: :delete, data: { confirm: 'Na pewno?' }%>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/layouts/_text.html.erb
<div role="tabpanel">
  <!-- Nav tabs nav-stacked, nav-pills or nav-tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#stats" aria-controls="stats" role="tab" data-toggle="tab">Statystyki</a></li>
    <li role="presentation"><a href="#charts" aria-controls="charts" role="tab" data-toggle="tab">Wykresy</a></li>
    <li role="presentation" class="active"><a href="#votes" aria-controls="votes" role="tab" data-toggle="tab">Głosy (<%= @count %>)</a></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="stats">
      <br><p><b>Wszystkich głosów: <%= @count %></b></p>
    </div>

    <div role="tabpanel" class="tab-pane" id="charts">

    </div>

    <div role="tabpanel" class="tab-pane active" id="votes">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Użytkownik</th>
            <th>Data</th>
            <th>Odpowiedź</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @votes.each do |vote| %>
            <tr>
              <td><%= vote.author %></td>
              <td><%= dateformat(vote.created_at) %></td>
              <td><%= vote.custom %></td>
              <td><%= link_to 'Usuń', vote, method: :delete, data: { confirm: 'Na pewno?' }%>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "mz_ankiety" %></title>
  <%= favicon_link_tag 'favicon2.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>

app/views/layouts/voting.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "mz_ankiety" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%# render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%# render 'layouts/footer' %>    

</body>
</html>